### ISSUE TITLE
Type Error: when I write the code as described in the README, it results in a type error

### ISSUE THREAD

**Issue by ari1357** [hwookim/storybook-addon-cookie#6]
### Describe the Type Error
---
When I write the code in TypeScript as described in the README, I encounter errors due to type mismatches in decorators.

### To Reproduce
---
storybook: v7.4.0
storybook-addon-cookie: 3.0.1

![スクリーンショット 2023-09-09 17 37 28](https://github.com/hwookim/storybook-addon-cookie/assets/49893085/04cfc9d8-b1f3-4fe6-88e5-71cc1196e17d)

### What I would like to request
---
please make it so that type errors do not occur !

### Other
---
The current state is that it works fine with just type errors, so the priority is not very high, I believe! Also, it was very helpful as there aren't many similar addons available. Thank you !!

Adding cookieDecorator to the decorators in preview.ts prevents errors from occurring, so I'm currently configuring it this way😏

.storybook/preview.ts
![スクリーンショット 2023-09-09 18 11 19（大）](https://github.com/hwookim/storybook-addon-cookie/assets/49893085/632b78f9-6a9e-4d57-8815-3940cb2478e4)

**Comment by hwookim** [comment]
@ari1357 
Oh, I'm sorry!

This is an error in the description in the README.
There is already a definition for [`preview.decorators`](https://github.com/hwookim/storybook-addon-cookie/blob/b7fffe42b9327048607b1791571b5935b1bfcf8a/packages/addon/src/preview.ts#L5) in the package, so you don't need to add any additional settings.
In fact, it's not even possible to apply the addon to a specific story because of the panel settings. 😢 

I've fixed the README, thanks for reporting the issue. 😄
